name: Azazel
version: '${project.version}'
main: net.lotho.Azazel
api-version: 1.18
authors: [ Lotho ]
softdepend:
  - PlaceholderAPI

commands:
  tags:
    aliases: [tag]
  tokens:
    aliases: [token]
